spring.datasource.url=jdbc:mysql://localhost:3308/dilanmotos?useSSL=false&serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false

springdoc.swagger-ui.path=/swagger-ui.html

google.api.key=AIzaSyDuB_9qi3Uz_dO1E6rL0vbxEacGec_bwFw
google.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent